name: Liquibase CI/CD - Proyecto UMG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Descargar e instalar Liquibase
        run: |
          mkdir liquibase-bin
          cd liquibase-bin
          curl -L -o liquibase.tar.gz https://github.com/liquibase/liquibase/releases/download/v5.0.1/liquibase-5.0.1.tar.gz
          tar -xvzf liquibase.tar.gz
          chmod +x liquibase
          ./liquibase --version
          cd ..

      - name: Descargar conector JDBC de MySQL
        run: |
          mkdir -p lib
          curl -L -o lib/mysql-connector-j-8.4.0.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.4.0/mysql-connector-j-8.4.0.jar

      - name: Ejecutar migraciones con Liquibase
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ./liquibase-bin/liquibase \
            --changeLogFile=changelog.sql \
            --classpath=lib/mysql-connector-j-8.4.0.jar \
            --url=$DB_URL \
            --username=$DB_USER \
            --password=$DB_PASSWORD \
            update
